GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJEemFydSBSaXpreSBGYXRoYW4gRm9ydHVuYSIsImVtYWlsIjoiZHphcnVyaXpreWJ1c2luZXNzMkBnbWFpbC5jb20iLCJpYXQiOjE3MDAwNjU0NjEsImV4cCI6MTcwMDA2NTQ4MX0.ehHFuvFHGg7T4Gva10Gue1BgNcDr7et4mveRzeFGCK0
###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Dzaru Rizky Fathan Fortuna",
  "email": "dzarurizkybusiness2@gmail.com",
  "password": "dzaru123",
  "confirmPassword": "dzaru123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
 "email": "dzarurizkybusiness@gmail.com",
 "password": "dzaru123" 
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout